<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Post;
use Carbon\Carbon;

class DefaultDataSeeder extends Seeder
{
    public function run(): void
    {
        if (Category::count() === 0) {
            $now = Carbon::now();
            $categories = [
                ['name' => 'Patagonia', 'description' => 'Región del sur argentino con montañas, lagos y glaciares.', 'created_at' => $now, 'updated_at' => $now],
                ['name' => 'Cuyo', 'description' => 'Tierra del vino y la cordillera en el oeste argentino.', 'created_at' => $now, 'updated_at' => $now],
                ['name' => 'Litoral', 'description' => 'Ríos, selvas y cataratas en el noreste del país.', 'created_at' => $now, 'updated_at' => $now],
                ['name' => 'Pampeana', 'description' => 'Llanuras fértiles, estancias y tradición gaucha.', 'created_at' => $now, 'updated_at' => $now],
                ['name' => 'Noroeste', 'description' => 'Paisajes áridos, salares, quebradas y cultura andina.', 'created_at' => $now, 'updated_at' => $now],
                ['name' => 'Noreste', 'description' => 'Clima cálido, ríos y gran diversidad natural.', 'created_at' => $now, 'updated_at' => $now]
            ];
            
            Category::insert($categories);
        }

        if (Post::count() < 15) {
            $now = Carbon::now();
            $posts = [
                // Patagonia (id 1)
                ['title' => 'Glaciar Perito Moreno', 'slug' => 'glaciar-perito-moreno', 'category_id' => 1, 'excerpt' => 'Un impresionante glaciar ubicado en el Parque Nacional Los Glaciares.', 'content' => 'Este coloso de hielo en movimiento es uno de los más accesibles del mundo. Sus desprendimientos son un espectáculo natural único en el corazón de la Patagonia. Con sus 60 metros de altura, el Glaciar Perito Moreno es un fenómeno geológico excepcional que atrae a miles de visitantes cada año. Los sonidos de los desprendimientos de hielo resuenan a través del lago Argentino, creando un espectáculo natural incomparable.', 'image_main' => 'images/patagonia11.jpg', 'image_2' => 'images/patagonia12.jpg', 'image_3' => 'images/patagonia13.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Torres del Paine', 'slug' => 'torres-del-paine', 'category_id' => 1, 'excerpt' => 'Parque natural en Chile famoso por sus montañas y lagos.', 'content' => 'Torres del Paine sorprende con imponentes macizos, lagos turquesa y senderos entre glaciares. Es un paraíso para amantes del trekking y la fotografía. Ubicado en la región de Magallanes, este parque nacional es uno de los destinos de senderismo más espectaculares de América del Sur. Las tres torres de granito se alzan majestuosamente sobre el paisaje patagónico.', 'image_main' => 'images/patagonia21.jpg', 'image_2' => 'images/patagonia22.jpg', 'image_3' => 'images/patagonia23.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Ushuaia - Fin del Mundo', 'slug' => 'ushuaia-fin-del-mundo', 'category_id' => 1, 'excerpt' => 'La ciudad más austral del mundo.', 'content' => 'Rodeada por montañas y el Canal Beagle, Ushuaia combina naturaleza, historia y aventura. Como la ciudad más austral del planeta, Ushuaia cautiva a los visitantes con su belleza salvaje y su atmósfera única. El Beagle Channel ofrece vistas espectaculares y oportunidades para observar fauna marina, mientras que el Parque Nacional Tierra del Fuego complementa la experiencia.', 'image_main' => 'images/patagonia31.jpg', 'image_2' => 'images/patagonia32.jpg', 'image_3' => 'images/patagonia33.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                
                // Cuyo (id 2) - 3 posts
                ['title' => 'Aconcagua', 'slug' => 'aconcagua', 'category_id' => 2, 'excerpt' => 'Hogar del cerro más alto de América.', 'content' => 'Con sus 6.962 metros, el Aconcagua domina la cordillera y atrae a montañistas de todo el mundo. Esta montaña colosal representa el pico más alto de América Latina y uno de los desafíos más codiciados de la montaña. Su ascenso requiere acclimatación y preparación, pero las vistas desde la cumbre son inolvidables.', 'image_main' => 'images/cuyo11.jpg', 'image_2' => 'images/cuyo12.jpg', 'image_3' => 'images/cuyo13.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Bodegas de Mendoza', 'slug' => 'bodegas-mendoza', 'category_id' => 2, 'excerpt' => 'Descubre los viñedos más famosos de Argentina.', 'content' => 'Mendoza es la región vinícola más importante de Argentina, con bodegas de clase mundial y paisajes de ensueño. Los valles mendocinos producen algunos de los mejores vinos de América del Sur, especialmente los Malbecs de renombre internacional. Recorrer las viñas, conocer el proceso de elaboración y degustar los vinos locales es una experiencia imprescindible.', 'image_main' => 'images/cuyo21.jpg', 'image_2' => 'images/cuyo22.jpg', 'image_3' => 'images/cuyo23.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'San Juan - Tierra de Sauces', 'slug' => 'san-juan-sauces', 'category_id' => 2, 'excerpt' => 'Descubre la provincia vecina de Mendoza.', 'content' => 'San Juan es una provincia productora de vino con paisajes desérticos espectaculares y rutas de peregrinación. El Parque Provincial Ischigualasto, con su Valle de la Luna, es un sitio de importancia paleontológica mundial. Los visitantes pueden disfrutar de aventuras en bicicleta, equitación y observación de dinosaurios.', 'image_main' => 'images/cuyo31.jpg', 'image_2' => 'images/cuyo32.jpg', 'image_3' => 'images/cuyo33.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                
                // Litoral (id 3) - 3 posts
                ['title' => 'Cataratas del Iguazú', 'slug' => 'cataratas-iguazu', 'category_id' => 3, 'excerpt' => 'Una de las maravillas naturales más impresionantes del mundo.', 'content' => 'Con más de 250 saltos de agua, las Cataratas del Iguazú son un espectáculo natural rodeado de selva subtropical. Declaradas Patrimonio de la Humanidad por la UNESCO, estas cataratas generan un estruendo ensordecedor y una bruma permanente. La vegetación selvática que las rodea es hábitat de miles de especies de flora y fauna.', 'image_main' => 'images/litoral11.jpg', 'image_2' => 'images/litoral12.jpg', 'image_3' => 'images/litoral13.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Parque Nacional El Palmar', 'slug' => 'parque-el-palmar', 'category_id' => 3, 'excerpt' => 'Parque conocido por sus palmeras yatay.', 'content' => 'Este parque resguarda extensos palmares yatay, fauna autóctona y senderos ideales para caminatas. Las palmeras yatay son una especie única de la región que pueden alcanzar más de 15 metros de altura. El parque ofrece ciclovías, miradores y áreas de pícnic para disfrutar de la naturaleza litoral.', 'image_main' => 'images/litoral21.jpg', 'image_2' => 'images/litoral22.jpg', 'image_3' => 'images/litoral23.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Misiones - Selva y Cultura', 'slug' => 'misiones-selva-cultura', 'category_id' => 3, 'excerpt' => 'Explora la provincia misionera de Argentina.', 'content' => 'Misiones es una provincia rica en biodiversidad y patrimonio cultural guaraní. Además de las Cataratas, ofrece reservas naturales, pueblos coloniales y experiencias ecoturísticas. Los visitantes pueden conocer la cultura guaraní, degustar la yerba mate local y explorar la selva subtropical.', 'image_main' => 'images/litoral31.jpg', 'image_2' => 'images/litoral32.jpg', 'image_3' => 'images/litoral33.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                
                // Pampeana (id 4) - 3 posts
                ['title' => 'La Plata', 'slug' => 'la-plata-ciudad', 'category_id' => 4, 'excerpt' => 'Conoce la capital de la Provincia de Buenos Aires.', 'content' => 'La Plata es una ciudad moderna y orgánica, diseñada como un cuadrícula perfecta con plazas y avenidas anchas. Fundada en 1882, esta ciudad es un ejemplo de planificación urbana sudamericana. Su arquitectura ecléctica, sus museos y sus bulevares amplios la hacen un destino cultural imprescindible. La Catedral Metropolitana y el Palacio Municipal son símbolos emblemáticos de su patrimonio.', 'image_main' => 'images/pampeana11.jpg', 'image_2' => 'images/pampeana12.jpg', 'image_3' => 'images/pampeana13.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Estancias Tradicionales', 'slug' => 'estancias-gauchas', 'category_id' => 4, 'excerpt' => 'Vive la tradición gaucha en las estancias bonaerenses.', 'content' => 'Las estancias son el corazón de la cultura gaucha, donde puedes montar a caballo y degustar comida criolla. Estas haciendas tradicionales conservan la esencia de la vida rural argentina. En una estancia, los visitantes pueden participar en actividades ganaderas, disfrutar de asados autóctonos y conocer a los gauchos que mantienen viva esta tradición milenaria.', 'image_main' => 'images/pampeana21.jpg', 'image_2' => 'images/pampeana22.jpg', 'image_3' => 'images/pampeana23.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Mar del Plata - Perla Atlántica', 'slug' => 'mar-del-plata-playas', 'category_id' => 4, 'excerpt' => 'Disfruta de las playas y el mar en Mar del Plata.', 'content' => 'Mar del Plata es la capital del turismo de playa de Argentina, con sus playas amplias, paseos marítimos y vida nocturna vibrante. La ciudad oferece gastronomía exquisita basada en mariscos frescos, casinos, museos y entretenimiento para toda la familia. El faro, el acuario y los balnearios son atracciones turísticas imprescindibles.', 'image_main' => 'images/pampeana31.jpg', 'image_2' => 'images/pampeana32.jpg', 'image_3' => 'images/pampeana33.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                
                // Noroeste (id 5) - 3 posts
                ['title' => 'Salta la Linda', 'slug' => 'salta-linda', 'category_id' => 5, 'excerpt' => 'Descubre la arquitectura colonial de Salta.', 'content' => 'Salta es conocida como "La Linda" por su hermosa arquitectura colonial y sus paisajes montañosos. La ciudad conserva su trazado colonial con la Plaza 9 de Julio como centro, rodeada de edificios de gran valor histórico. El Cabildo, la Catedral Metropolitana y las iglesias coloniales son tesoros arquitectónicos que reflejan la historia de la conquista y colonización española.', 'image_main' => 'images/salta.png', 'image_2' => 'images/salta.png', 'image_3' => 'images/salta.png', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Jujuy - La Quebrada', 'slug' => 'jujuy-quebrada', 'category_id' => 5, 'excerpt' => 'Paisajes de ensueño en la Quebrada de Humahuaca.', 'content' => 'La Quebrada de Humahuaca es un valle de importancia arqueológica y cultural, declarado Patrimonio de la Humanidad. A lo largo de los 155 kilómetros del valle, pueblos coloridos como Tilcara, Purmamarca y Maimará presenten arquitectura tradicional y arte andino. Los paisajes montañosos con sus cerros multicolores son especialmente espectaculares.', 'image_main' => 'images/noroeste21.jpg', 'image_2' => 'images/noroeste22.jpg', 'image_3' => 'images/noroeste23.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Catamarca - Puna y Valles', 'slug' => 'catamarca-puna', 'category_id' => 5, 'excerpt' => 'Explora los paisajes montañosos de Catamarca.', 'content' => 'Catamarca ofrece paisajes variados desde la Puna hasta los valles fértiles, con una riqueza arqueológica que incluye ruinas preincaicas. El Monte de las Siete Colores de Purmamarca es un ícono visual de la región. Los visitantes pueden disfrutar de trekking, observación de fauna andina y experiencias culturales con comunidades indígenas.', 'image_main' => 'images/noroeste31.jpg', 'image_2' => 'images/noroeste32.jpg', 'image_3' => 'images/noroeste33.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                
                // Noreste (id 6) - 3 posts
                ['title' => 'Puerto Iguazú', 'slug' => 'puerto-iguazu', 'category_id' => 6, 'excerpt' => 'Puerta de entrada a las Cataratas del Iguazú.', 'content' => 'Puerto Iguazú es una ciudad turística que ofrece acceso a las cataratas y la selva subtropical. Ubicada en el triángulo de las tres fronteras (Argentina, Brasil y Paraguay), es un centro estratégico para explorar la región. La ciudad cuenta con hotelería variada, restaurantes con sabor local y tiendas de artesanías indígenas.', 'image_main' => 'images/noreste11.jpg', 'image_2' => 'images/noreste12.jpg', 'image_3' => 'images/noreste13.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Esteros del Iberá', 'slug' => 'esteros-ibera', 'category_id' => 6, 'excerpt' => 'Humedales únicos de América del Sur.', 'content' => 'Los Esteros del Iberá son uno de los humedales más importantes del continente, hogar de fauna diversa. Con una superficie de casi 13.000 kilómetros cuadrados, estos humedales albergan cocodrilos, caimanes, ciervos de los pantanos y cientos de especies de aves. Es un paraíso para la observación de vida silvestre y la fotografía de naturaleza.', 'image_main' => 'images/noreste21.jpg', 'image_2' => 'images/noreste22.jpg', 'image_3' => 'images/noreste23.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now],
                ['title' => 'Corrientes - Río y Tradición', 'slug' => 'corrientes-rio-tradicion', 'category_id' => 6, 'excerpt' => 'Descubre la provincia de Corrientes.', 'content' => 'Corrientes es una provincia ribereña rica en tradiciones, folclore y naturaleza. Famosa por su folclore musical, sus procesiones religiosas y sus paisajes fluviales. Los visitantes pueden navegar por el río Paraná, visitar pueblos coloniales y disfrutar de la gastronomía local con el famoso tereré.', 'image_main' => 'images/noreste31.jpg', 'image_2' => 'images/noreste32.jpg', 'image_3' => 'images/noreste33.jpg', 'published' => 1, 'created_at' => $now, 'updated_at' => $now]
            ];
            
            foreach ($posts as $post) {
                Post::updateOrCreate(['slug' => $post['slug']], $post);
            }
        }
    }
}
